"""
Voice call simulator for the Parent Outreach Agent.
Simulates realistic phone conversations with predefined scenarios.

In production, this would be replaced by Twilio/Vapi/Retell integration.
"""
from __future__ import annotations

import asyncio
import logging
from datetime import datetime
from typing import Optional

from models.parent import ParentRecord

logger = logging.getLogger(__name__)


# ──────────────── Predefined Scenario Responses ────────────────

SCENARIO_SCRIPTS = {
    "answers_all": [
        {"role": "system", "content": "[Phone rings... Parent answers]"},
        {"role": "parent", "content": "Hello?"},
        # Agent introduces themselves (generated by LLM)
        {"role": "parent", "content": "Oh yes, hi! Sure, I have a moment. What do you need?"},
        # Agent asks for missing fields
        {
            "role": "parent",
            "content": (
                "Sure! My email is sarah.johnson@gmail.com. "
                "My mobile is +1-555-8801. "
                "Emma goes to Lincoln Elementary School. "
                "We'd prefer Wednesday, around 4:30 PM for the group event. "
                "Also, Emma has a peanut allergy — please note that down."
            ),
        },
        # Agent confirms and thanks
        {"role": "parent", "content": "Sounds great, thank you! Looking forward to it."},
    ],
    "no_answer_whatsapp": [
        {"role": "system", "content": "[Phone rings... No answer after 30 seconds]"},
        {"role": "system", "content": "[Call goes to voicemail]"},
        {"role": "system", "content": "[Agent hangs up — will trigger WhatsApp follow-up]"},
    ],
    "partial_info": [
        {"role": "system", "content": "[Phone rings... Parent answers]"},
        {"role": "parent", "content": "Hello, who is this?"},
        # Agent introduces
        {"role": "parent", "content": "Oh right, for Arjun. Yes, what do you need?"},
        # Agent asks for missing fields
        {
            "role": "parent",
            "content": (
                "My mobile number is +1-555-7703. "
                "He goes to... hold on, I'm getting another call. "
                "Can I just — actually I need to take this. Sorry!"
            ),
        },
        {"role": "system", "content": "[Parent hangs up abruptly]"},
    ],
    "callback_requested": [
        {"role": "system", "content": "[Phone rings... Parent answers]"},
        {"role": "parent", "content": "Hello?"},
        # Agent introduces
        {
            "role": "parent",
            "content": (
                "Hi, yes this is James. Look, I'm actually in a meeting right now. "
                "Can you call me back later today? Maybe around 6 PM would work. Thanks!"
            ),
        },
        {"role": "system", "content": "[Parent ends call]"},
    ],
    "wrong_number": [
        {"role": "system", "content": "[Phone rings... Someone answers]"},
        {"role": "parent", "content": "Hello?"},
        # Agent introduces and asks for parent
        {
            "role": "parent",
            "content": (
                "I'm sorry, who? There's no Lisa here. "
                "I think you have the wrong number. "
                "This is Bob's Auto Shop."
            ),
        },
        {"role": "parent", "content": "No problem, goodbye."},
    ],
    "opt_out": [
        {"role": "system", "content": "[Phone rings... Parent answers]"},
        {"role": "parent", "content": "What is it?"},
        # Agent introduces
        {
            "role": "parent",
            "content": (
                "Look, I've already told you people — I'm not interested. "
                "Please stop calling me. Remove my number from your list. "
                "I don't want to be contacted again."
            ),
        },
        {"role": "system", "content": "[Parent hangs up]"},
    ],
}


class VoiceSimulator:
    """
    Simulates voice calls for testing.
    Each call follows a predefined script based on the parent's scenario tag.

    In production, this class would be swapped with:
    - TwilioVoiceClient (Twilio Programmable Voice)
    - VapiClient (Vapi.ai)
    - RetellClient (Retell AI)
    """

    def __init__(self):
        logger.info("Voice Simulator initialized (simulation mode)")

    async def make_call(
        self,
        parent: ParentRecord,
        scenario: str = "answers_all",
    ) -> dict:
        """
        Simulate a voice call to a parent.

        Returns:
            {
                "answered": bool,
                "conversation": list of {"role": str, "content": str},
                "duration_seconds": float,
                "scenario": str,
            }
        """
        script = SCENARIO_SCRIPTS.get(scenario, SCENARIO_SCRIPTS["answers_all"])

        logger.info(f"📞 Calling {parent.parent_name} at {parent.phone}...")
        logger.info(f"   Scenario: {scenario}")

        # Simulate call delay
        await asyncio.sleep(0.5)

        # Check if parent answered (no_answer scenario has no parent messages)
        answered = any(msg["role"] == "parent" for msg in script)

        # Calculate simulated duration
        if not answered:
            duration = 32.0  # Ring time + voicemail
        elif scenario == "callback_requested":
            duration = 25.0
        elif scenario in ("wrong_number", "opt_out"):
            duration = 18.0
        elif scenario == "partial_info":
            duration = 45.0
        else:
            duration = 90.0  # Full conversation

        conversation = []
        for msg in script:
            if msg["role"] == "system":
                logger.info(f"   {msg['content']}")
            else:
                conversation.append(msg)
                speaker_emoji = "🤖" if msg["role"] == "agent" else "👤"
                logger.info(f"   {speaker_emoji} {msg['role'].title()}: {msg['content'][:80]}...")

        return {
            "answered": answered,
            "conversation": conversation,
            "duration_seconds": duration,
            "scenario": scenario,
        }

    async def hangup(self):
        """Simulate ending a call."""
        logger.info("📞 Call ended")
        await asyncio.sleep(0.1)
